# Generated by Django 5.2.7 on 2025-10-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('journalist', 'Journalist')], max_length=255),
        ),
    ]
