# Generated by Django 5.2.7 on 2025-11-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profileUrl',
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('journalist', 'Journalist'), ('user', 'User')], max_length=255),
        ),
    ]
