# Generated by Django 5.2.7 on 2025-11-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_category_alter_articles_media_and_more'),
        ('users', '0005_save'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='save',
            new_name='User_Saves',
        ),
        migrations.AlterUniqueTogether(
            name='user_saves',
            unique_together={('user', 'article')},
        ),
        migrations.AlterModelTable(
            name='user_saves',
            table='user_save',
        ),
    ]
