# Generated by Django 5.2.7 on 2025-11-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_save_user_saves_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Saves',
        ),
    ]
