# Generated by Django 5.2.7 on 2025-11-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_user_saves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('journalist', 'Journalist'), ('user', 'User'), ('admin', 'Admin')], max_length=255),
        ),
    ]
