# Generated by Django 5.2.7 on 2025-11-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='media',
            field=models.JSONField(default=list, null=True),
        ),
    ]
