# Generated by Django 5.2.7 on 2025-11-03 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_category_alter_articles_media_and_more'),
        ('users', '0007_delete_user_saves'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('liked', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='articles.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_interactions', to='users.users')),
            ],
            options={
                'db_table': 'article_interactions',
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Commentslikes',
        ),
    ]
